version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_db
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./sql-scripts/init_table.sql:/docker-entrypoint-initdb.d/init_table.sql


## docker-compose exec mysql bash
## mysql -uroot -p orders_db