// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewOrder struct {
	Name        string  `json:"name"`
	OrderType   string  `json:"orderType"`
	Description *string `json:"description,omitempty"`
}

type Order struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	OrderType   string  `json:"orderType"`
	Description *string `json:"description,omitempty"`
}

type Query struct {
}
